# FROM node:20-alpine

# WORKDIR /app

# COPY package.json ./

# RUN npm uninstall chart.js react-chartjs-2
#  RUN npm install chart.js@^4.5.1 react-chartjs-2@^5.3.1


# RUN npm install --legacy-peer-deps --force && \
#     npm install @mui/x-date-pickers date-fns @emotion/react @emotion/styled @mui/material

# RUN npm install --save-dev @vitejs/plugin-react

# # RUN npm install -g vite

# COPY . .

# RUN npm run build

# EXPOSE 3000

# CMD ["npm", "run", "dev"]

FROM node:20-alpine

WORKDIR /app

COPY package.json ./

RUN npm install --legacy-peer-deps

COPY . .

RUN npm run build

EXPOSE 5173

CMD ["npm", "run", "dev","--","--host"]
