FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY scripts/ scripts/
COPY cron/monthly /etc/cron.d/monthly
COPY entrypoint.sh /entrypoint.sh

RUN apt-get update \
 && apt-get install -y cron \
 && chmod 0644 /etc/cron.d/monthly \
 && touch /var/log/cron.log \
 && rm -rf /var/lib/apt/lists/*

 CMD python scripts/restart_db.py && cron -f
